name: test

channels:
  - conda-forge
  - defaults

dependencies:

    # Core dependencies
  - python
  - pip

  - openff-toolkit-base >=0.9.2
  - pytorch
  - pydantic
  - click

  # --------- openff-system ---------
  - openff-utilities
  - pint
  # --------- openff-system ---------

  # --------- openff-qcsubmit ---------
  - qcportal
  - torsiondrive
  - cachetools
  - tqdm
  - pyyaml
  # --------- openff-qcsubmit ---------

    # Optional dependencies
  - rdkit
  - ambertools

    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Development
  - isort
  - black
  - flake8

  - pip:

      - git+git://github.com/openforcefield/openff-units.git
      - git+git://github.com/openforcefield/openff-system.git
      - git+git://github.com/openforcefield/openff-qcsubmit.git
      - git+git://github.com/SimonBoothroyd/smirnoffee.git
