name: test

channels:
  - conda-forge
  - defaults
  - simonboothroyd

dependencies:

    # Core dependencies
  - python
  - pip

  - click

  - openff-toolkit-base >=0.9.2
  - openff-interchange ==0.1.0

  - openff-utilities
  - openff-units

  - openff-qcsubmit >= 0.2.2

  - smirnoffee >=0.0.1a2
  - pytorch >= 1.9.0

  - pydantic

    # Optional dependencies
  - rdkit
  - ambertools

  - geometric

    # Testing
  - pytest
  - pytest-cov
  - codecov

    # Development
  - isort
  - black
  - flake8
