repos:
  - repo: local
    hooks:
      - id: ruff
        name: "[Package] Formatting"
        language: system
        entry: ruff
        args: [ check ]
        files: \.py$

      - id: ruff-examples
        name: "[Examples] Formatting"
        language: system
        entry: nbqa ruff
        files: examples/.+\.ipynb$
