name: descent

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - smee >=0.8.0

  - pytorch
  - pydantic
  - pyarrow
  - datasets

  ### Levenberg Marquardt
  - scipy

  # Optional packages
  - rdkit
  - matplotlib-base
  - panel

  # Examples
  - jupyter
  - nbconvert

  # Training
#  - ray-default
  - tensorboard
  - tensorboardX

  # Dev / Testing
  - ambertools
  - rdkit

  - versioneer

  - pre-commit
  - isort
  - black
  - flake8
  - flake8-pyproject
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov
