name: descent

channels:
  - conda-forge

dependencies:

  - python >=3.10
  - pip

  # Core packages
  - smee >=0.4.0

  - pytorch
  - pydantic
  - pyarrow

  ### Levenberg Marquardt
  - scipy

  # Optional packages
  - rdkit
  - matplotlib-base

  # Examples
  - jupyter
  - nbconvert

  # Dev / Testing
  - ambertools
  - rdkit

  - versioneer

  - pre-commit
  - isort
  - black
  - flake8
  - flake8-pyproject
  - nbqa

  - pytest
  - pytest-cov
  - pytest-mock

  - codecov
