name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only descent
          isort --recursive --check-only examples
          isort --recursive --check-only integration-tests

      - name: Run black
        run: |
          black descent --check
          black examples --check
          black integration-tests --check

      - name: Run flake8
        run: |
          flake8 descent
          flake8 examples
          flake8 integration-tests
